# Generated by Django 5.0.6 on 2024-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("third_name", models.CharField(blank=True, max_length=100, null=True)),
                ("surname", models.CharField(max_length=100)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Female"), (2, "Male"), (3, "Other")]
                    ),
                ),
                ("born", models.DateField(blank=True, null=True)),
                ("died", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
