# Generated by Django 5.0.6 on 2024-07-09 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Partner"),
                            (2, "Mother"),
                            (3, "Father"),
                            (4, "Stepmother"),
                            (5, "Stepfather"),
                            (6, "Wife"),
                            (7, "Husband"),
                            (8, "Brother"),
                            (9, "Sister"),
                            (10, "Half-bother"),
                            (11, "Half-sister"),
                            (12, "Adopted son"),
                            (13, "Adopted daughter"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="member.member",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="member.member",
                    ),
                ),
            ],
        ),
    ]
