# Generated by Django 5.0.6 on 2024-07-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0002_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="relation_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Partner"),
                    (2, "Mother"),
                    (3, "Father"),
                    (4, "Daughter"),
                    (5, "Son"),
                    (6, "Child"),
                    (7, "Stepmother"),
                    (8, "Stepfather"),
                    (9, "Wife"),
                    (10, "Husband"),
                    (11, "Brother"),
                    (12, "Sister"),
                    (13, "Sibling"),
                    (14, "Half-bother"),
                    (15, "Half-sister"),
                    (16, "Adopted son"),
                    (17, "Adopted daughter"),
                ]
            ),
        ),
    ]
