# Generated by Django 5.0.6 on 2024-07-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0003_alter_relation_relation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Female"), (2, "Male")]
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="relation_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Partner"),
                    (2, "Mother"),
                    (3, "Father"),
                    (4, "Daughter"),
                    (5, "Son"),
                    (6, "Wife"),
                    (7, "Husband"),
                    (8, "Brother"),
                    (9, "Sister"),
                    (10, "Stepmother"),
                    (11, "Stepfather"),
                    (12, "Stepson"),
                    (13, "Stepdaughter"),
                    (14, "Half-bother"),
                    (15, "Half-sister"),
                    (16, "Sibling"),
                    (17, "Adopted son"),
                    (18, "Adopted daughter"),
                    (19, "Parent"),
                ]
            ),
        ),
    ]
